[tool.poetry]
name = "devitalik-zx"
version = "0.1.0"
description = "DeVitalik ZX Bot"

[tool.poetry.dependencies]
python = "^3.9"
prompt-toolkit = "^3.0.0"
tweepy = "^4.14.0"
openai = "^1.3.0"
anthropic-sdk = "^0.5.0"
pydantic = "^2.0.0"
